# Generated by Django 3.0.2 on 2020-01-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='product/media')),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=200)),
                ('choice', models.BooleanField(default=False)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Product', to='product.Category')),
            ],
        ),
    ]
