# Generated by Django 3.0.2 on 2020-01-24 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='user/seller')),
                ('contact', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('street_address1', models.CharField(max_length=256)),
                ('street_address2', models.CharField(max_length=256)),
                ('city', models.CharField(choices=[('KATHMANDU', 'Kathmandu'), ('BHAKTAPUR', 'Bhaktapur'), ('LALITPUR', 'Lalitpur')], max_length=256)),
                ('province', models.CharField(choices=[('1', 'Province 1'), ('2', 'Province 2'), ('3', 'Bagmati'), ('4', 'Gandaki'), ('5', 'Province 5'), ('6', 'Karnali'), ('7', 'Sudurpaschim')], max_length=15)),
            ],
        ),
    ]
